---
exclude_paths:
  - "archive/**"
  - "private/**"
  - "re_out/**"
  - "DerivedData/**"
  - ".build/**"
  - ".swiftpm/**"
  - ".pytest_cache/**"
  - ".ruff_cache/**"
  - ".mypy_cache/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/*.pyo"
  - "Sources/opus-1.5.2/.github/**"
  - "Sources/opus-1.5.2/.gitlab-ci.yml"
  - "Sources/opus-1.5.2/.gitmodules"
  - "Sources/opus-1.5.2/celt/tests/**"
  - "Sources/opus-1.5.2/celt/arm/**"
  - "Sources/opus-1.5.2/celt/x86/**"
  - "Sources/opus-1.5.2/silk/arm/**"
  - "Sources/opus-1.5.2/silk/tests/**"
  - "Sources/opus-1.5.2/silk/x86/**"
  - "Sources/opus-1.5.2/tests/**"
  - "Sources/opus-1.5.2/dnn/**"
  - "Sources/opus-1.5.2/scripts/**"
  - "Sources/opus-1.5.2/training/**"
  - "Sources/opus-1.5.2/doc/**"
  - "Sources/opus-1.5.2/cmake/**"
  - "Sources/opus-1.5.2/m4/**"
  - "Sources/opus-1.5.2/meson/**"
  - "Sources/opus-1.5.2/autogen.bat"
  - "Sources/opus-1.5.2/autogen.sh"
  - "Sources/opus-1.5.2/CMakeLists.txt"
  - "Sources/opus-1.5.2/configure.ac"
  - "Sources/opus-1.5.2/configure"
  - "Sources/opus-1.5.2/Makefile.mips"
  - "Sources/opus-1.5.2/Makefile.unix"
  - "Sources/opus-1.5.2/Makefile.am"
  - "Sources/opus-1.5.2/Makefile.in"
  - "Sources/opus-1.5.2/meson.build"
  - "Sources/opus-1.5.2/meson_options.txt"
  - "Sources/opus-1.5.2/opus-uninstalled.pc.in"
  - "Sources/opus-1.5.2/opus.m4"
  - "Sources/opus-1.5.2/opus.pc.in"
  - "Sources/opus-1.5.2/celt_headers.mk"
  - "Sources/opus-1.5.2/celt_sources.mk"
  - "Sources/opus-1.5.2/silk_headers.mk"
  - "Sources/opus-1.5.2/silk_sources.mk"
  - "Sources/opus-1.5.2/opus_headers.mk"
  - "Sources/opus-1.5.2/opus_sources.mk"
  - "Sources/opus-1.5.2/lpcnet_headers.mk"
  - "Sources/opus-1.5.2/lpcnet_sources.mk"
  - "Sources/opus-1.5.2/src/opus_compare.c"
  - "Sources/opus-1.5.2/src/repacketizer_demo.c"
  - "Sources/opus-1.5.2/silk/debug.h"
  - "Sources/opus-1.5.2/silk/MacroDebug.h"
  - "Sources/xs_ref_sw_ed2/extras/**"
  - "Sources/xs_ref_sw_ed2/programs/**"
  - "Sources/xs_ref_sw_ed2/std/**"
  - "Sources/xs_ref_sw_ed2/CMakeLists.txt"
  - "Sources/xs_ref_sw_ed2/libjxs/CMakeLists.txt"
  - "Sources/xs_ref_sw_ed2/libjxs/src/msbpack.c"
