// Declares external-connector command rows separately so connector CLI coverage can be audited without expanding the core runtime table.
import Foundation

let milestoneRuntimeExternalCommands: [CLICommandInventoryEntry] = [
    command(
        "external-connector-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorReportTests.swift"]
    ),
    command(
        "external-connector-report-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorReportTests.swift"]
    ),
    command(
        "external-connector-session-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        [
            "Tests/OpenLolaCoreTests/ExternalConnectorSessionTests.swift",
            "Tests/OpenLolaCoreTests/ExternalConnectorAvMatrixTests.swift"
        ]
    ),
    command(
        "external-connector-connection-plan-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorConnectionPlanTests.swift"]
    ),
    command(
        "external-connector-nmp-plan-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorNmpPlanTests.swift"]
    ),
    command(
        "external-connector-nmp-preflight-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorNmpPreflightTests.swift"]
    ),
    command(
        "external-connector-nmp-endpoint-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorNmpEndpointRunTests.swift"]
    ),
    command(
        "external-connector-nmp-workflow-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorNmpWorkflowTests.swift"]
    ),
    command(
        "external-connector-executable-preflight-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorExecutablePreflightTests.swift"]
    ),
    command(
        "lola-capture-decode",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityCaptureReportTests.swift"]
    ),
    command(
        "lola-packet-fixture-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityPacketFixtureTests.swift"]
    ),
    command(
        "lola-media-report-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityMediaSessionTests.swift"]
    ),
    command(
        "lola-raw-link-tx-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityMediaSessionTests.swift"]
    ),
    command(
        "lola-raw-link-rx-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityMediaSessionTests.swift"]
    ),
    command(
        "lola-udp-media-tx-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityMediaSessionTests.swift"]
    ),
    command(
        "lola-udp-media-rx-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityMediaSessionTests.swift"]
    ),
    command(
        "validate-external-connector-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorReportTests.swift"]
    ),
    command(
        "validate-external-connector-session-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        [
            "Tests/OpenLolaCoreTests/ExternalConnectorSessionTests.swift",
            "Tests/OpenLolaCoreTests/ExternalConnectorAvMatrixTests.swift"
        ]
    ),
    command(
        "validate-external-connector-connection-plan",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorConnectionPlanTests.swift"]
    ),
    command(
        "validate-external-connector-nmp-plan",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorNmpPlanTests.swift"]
    ),
    command(
        "validate-external-connector-nmp-preflight",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorNmpPreflightTests.swift"]
    ),
    command(
        "validate-external-connector-nmp-endpoint-run",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorNmpEndpointRunTests.swift"]
    ),
    command(
        "validate-external-connector-nmp-workflow",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorNmpWorkflowTests.swift"]
    ),
    command(
        "validate-external-connector-executable-preflight-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/ExternalConnectorExecutablePreflightTests.swift"]
    ),
    command(
        "validate-lola-capture-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityCaptureReportTests.swift"]
    ),
    command(
        "validate-lola-packet-fixture-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityPacketFixtureTests.swift"]
    ),
    command(
        "validate-lola-media-session-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaCompatibilityMediaSessionTests.swift"]
    ),
    command(
        "release-hardening-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ReleaseHardeningTests.swift"]
    ),
    command(
        "release-hardening-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/ReleaseHardeningTests.swift"]
    ),
    command(
        "open-source-release-readiness-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/OpenSourceReleaseReadinessTests.swift"]
    ),
    command(
        "drift-plc-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/DriftPlcReportTests.swift"]
    )
]
