// Enumerates milestone and runtime CLI commands with their parsers, source owners, and verification references for inventory reporting.
import Foundation

let milestoneRuntimeCommands: [CLICommandInventoryEntry] =
    milestoneRuntimeCoreCommands + milestoneRuntimeExternalCommands

private let milestoneRuntimeCoreCommands: [CLICommandInventoryEntry] = [
    command(
        "udp-pcm-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/UdpPcmPacketTests.swift"]
    ),
    command(
        "udp-pcm-route-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/UdpPcmRouteReportTests.swift"]
    ),
    command(
        "route-certification-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/MacToMacRouteCertificationTests.swift"]
    ),
    command(
        "latency-benchmark-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LatencyBenchmarkReportTests.swift"]
    ),
    command(
        "latency-tuning-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LatencyTuningReportTests.swift"]
    ),
    command(
        "latency-profile-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LatencyProfileTests.swift"]
    ),
    command(
        "realtime-audio-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/RealtimeAudioEngineTests.swift"]
    ),
    command(
        "madi-tx-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/MadiTransmitTests.swift"]
    ),
    command(
        "drift-plc-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/DriftPlcReportTests.swift"]
    ),
    command(
        "drift-plc-certification-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/DriftPlcFixedTargetCertificationFixtures+TestSupport.swift"]
    ),
    command(
        "aoip-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/AoipEvaluationReportTests.swift"]
    ),
    command(
        "network-aoip-certification-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/NetworkAoipCertificationFixtures+TestSupport.swift"]
    ),
    command(
        "video-capture-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/VideoCaptureReportTests.swift"]
    ),
    command(
        "video-capture-inventory",
        .inventory,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/VideoCaptureReportTests.swift"]
    ),
    command(
        "video-capture-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/VideoCaptureReportTests.swift"]
    ),
    command(
        "video-transport-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/VideoTransportRunnerTests.swift"]
    ),
    command(
        "video-transport-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/VideoTransportRunnerTests.swift"]
    ),
    command(
        "integrated-av-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/IntegratedAvReportTests.swift"]
    ),
    command(
        "integrated-av-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/IntegratedAvReportTests.swift"]
    ),
    command(
        "integrated-profile-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/IntegratedProfileReportTests.swift"]
    ),
    command(
        "integrated-profile-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        [
            "Tests/OpenLolaCoreTests/IntegratedProfileReportTests.swift",
            "Tests/OpenLolaCoreTests/IntegratedProfileRunEvidenceTests.swift"
        ]
    ),
    command(
        "hardware-validation-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/HardwareValidationReportTests.swift"]
    ),
    command(
        "hardware-validation-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/HardwareValidationReportTests.swift"]
    ),
    command(
        "osc-cue-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/OscCueReportTests.swift"]
    ),
    command(
        "osc-cue-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/OscCueReportTests.swift"]
    ),
    command(
        "osc-cue-external-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/OscCueReportTests.swift"]
    ),
    command(
        "atem-readonly-probe",
        .probe,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/IntegratedAvReportTests.swift"]
    ),
    command(
        "lighting-gate-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LightingFixtureGateTests.swift"]
    ),
    command(
        "lighting-gate-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/LightingFixtureGateTests.swift"]
    ),
    command(
        "native-app-shell-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/NativeAppShellTests.swift"]
    ),
    command(
        "native-app-shell-surface-probe",
        .probe,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/NativeAppShellTests.swift"]
    ),
    command(
        "native-app-runtime-smoke",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/NativeAppShellTests.swift"]
    ),
    command(
        "recording-session-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/RecordingSessionArtifactTests.swift"]
    ),
    command(
        "recording-session-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/RecordingSessionArtifactTests.swift"]
    ),
    command(
        "packaging-field-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/PackagingFieldTestTests.swift"]
    ),
    command(
        "packaging-field-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/PackagingFieldTestTests.swift"]
    ),
    command(
        "field-runtime-proof-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/FieldReadyRuntimeProofTests.swift"]
    ),
    command(
        "field-readiness-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/FieldReadyRuntimeProofTests.swift"]
    ),
    command(
        "field-runtime-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/FieldReadyRuntimeProofTests.swift"]
    ),
    command(
        "faster-than-lola-closure-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/FasterThanLoLaClosureTests.swift"]
    ),
    command(
        "faster-than-lola-closure-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        ["Tests/OpenLolaCoreTests/FasterThanLoLaClosureTests.swift"]
    )
]
