// Enumerates milestone and runtime CLI commands with their parsers, source owners, and verification references for inventory reporting.
import Foundation

let milestoneRuntimeCommands: [CLICommandInventoryEntry] =
    milestoneRuntimeCoreCommands + milestoneRuntimeExternalCommands

private let milestoneRuntimeCoreCommands: [CLICommandInventoryEntry] = [
    command(
        "udp-pcm-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "udp-pcm-route-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "route-certification-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "latency-benchmark-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "latency-tuning-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "latency-profile-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "realtime-audio-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "madi-tx-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "drift-plc-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "drift-plc-certification-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "aoip-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "network-aoip-certification-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "video-capture-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "video-capture-inventory",
        .inventory,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "video-capture-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "video-transport-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "video-transport-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "integrated-av-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "integrated-av-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "integrated-profile-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "integrated-profile-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "hardware-validation-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "hardware-validation-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "osc-cue-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "osc-cue-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "osc-cue-external-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "atem-readonly-probe",
        .probe,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "lighting-gate-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "lighting-gate-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "native-app-shell-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "native-app-shell-surface-probe",
        .probe,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "native-app-runtime-smoke",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "recording-session-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "recording-session-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "packaging-field-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "packaging-field-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "field-runtime-proof-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "field-readiness-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "field-runtime-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "faster-than-lola-closure-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "faster-than-lola-closure-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    )
]
