// Catalogs network, NAT, UDP, and direct-peer commands in a dedicated row table for route-specific completeness checks.
import Foundation

let networkCommands: [CLICommandInventoryEntry] = [
    command(
        "device-inventory",
        .inventory,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-reference-rig-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-loopback-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-rme-fastest-audio-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-realtime-audio-engine-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-audio-loopback-run-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "audio-loopback-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-udp-pcm-packet",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-route-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-route-certification-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-udp-pcm-loopback-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-udp-pcm-loopback-session",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "udp-pcm-route-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "udp-pcm-loopback-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "udp-pcm-loopback-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-network-diagnostics-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "network-diagnostics-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-nat-friendly-route-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-mac-to-mac-connection-establishment-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "mac-to-mac-connection-preflight-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-direct-p2p-session-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "verify-direct-p2p-session-evidence-bundle",
        .probe,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-direct-p2p-mesh-topology-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-direct-p2p-mesh-runtime-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-direct-p2p-two-peer-plan-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-direct-p2p-two-peer-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-direct-p2p-two-peer-prototype-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "validate-direct-p2p-two-peer-local-run-report",
        .validator,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "nat-rendezvous-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "nat-relay-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "nat-rendezvous-forwarder-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "nat-friendly-route-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "nat-friendly-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "nat-rendezvous-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "nat-rendezvous-forwarder-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "nat-relay-fallback-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "direct-p2p-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "direct-p2p-mesh-topology-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "direct-p2p-mesh-runtime-localhost-smoke",
        .localhostSmoke,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "direct-p2p-two-peer-plan-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "direct-p2p-two-peer-report",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "direct-p2p-two-peer-prototype-report",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "direct-p2p-two-peer-local-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    ),
    command(
        "direct-p2p-session-run",
        .run,
        "Sources/open-lola/Commands/Network/NetworkCommands.swift",
        []
    )
]
