// Validates CLICommandInventoryValidationCommands acceptance rules, keeping failure policy close to its contract rather than the runtime path.
import Foundation

let milestoneValidationCommands: [CLICommandInventoryEntry] = [
    command(
        "validate-latency-benchmark-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-rx-buffer-benchmark-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-latency-tuning-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-drift-plc-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-drift-plc-certification-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-aoip-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-network-aoip-certification-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-video-capture-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-video-capture-inventory",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-video-transport-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-integrated-av-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-integrated-profile-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-hardware-validation-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-osc-cue-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-atem-control-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-lighting-gate-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-native-app-shell-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-native-app-shell-surface-probe-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-recording-session-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-packaging-field-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-field-runtime-proof",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-lola-parity-deferred-ledger",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-faster-than-lola-closure",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-goal-codewise-closure-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-goal-runtime-evidence-template-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-goal-runtime-preflight-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-goal-completion-audit-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-current-evidence-status-matrix-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-release-hardening-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-open-source-release-readiness-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    )
]
