// Validates CLICommandInventoryValidationCommands acceptance rules, keeping failure policy close to its contract rather than the runtime path.
import Foundation

let milestoneValidationCommands: [CLICommandInventoryEntry] = [
    command(
        "validate-latency-benchmark-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/LatencyBenchmarkReportTests.swift"]
    ),
    command(
        "validate-rx-buffer-benchmark-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/RxBufferingTests.swift"]
    ),
    command(
        "validate-latency-tuning-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/LatencyTuningReportTests.swift"]
    ),
    command(
        "validate-drift-plc-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/DriftPlcReportTests.swift"]
    ),
    command(
        "validate-drift-plc-certification-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/DriftPlcFixedTargetCertificationFixtures+TestSupport.swift"]
    ),
    command(
        "validate-aoip-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/AoipEvaluationReportTests.swift"]
    ),
    command(
        "validate-network-aoip-certification-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/NetworkAoipCertificationFixtures+TestSupport.swift"]
    ),
    command(
        "validate-video-capture-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/VideoCaptureReportTests.swift"]
    ),
    command(
        "validate-video-capture-inventory",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/VideoCaptureReportTests.swift"]
    ),
    command(
        "validate-video-transport-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/VideoTransportReportTests.swift"]
    ),
    command(
        "validate-integrated-av-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/IntegratedAvReportTests.swift"]
    ),
    command(
        "validate-integrated-profile-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        [
            "Tests/OpenLolaCoreTests/IntegratedProfileReportTests.swift",
            "Tests/OpenLolaCoreTests/IntegratedProfileRunEvidenceTests.swift"
        ]
    ),
    command(
        "validate-hardware-validation-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/HardwareValidationReportTests.swift"]
    ),
    command(
        "validate-osc-cue-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/OscCueReportTests.swift"]
    ),
    command(
        "validate-atem-control-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/IntegratedAvReportTests.swift"]
    ),
    command(
        "validate-lighting-gate-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/LightingFixtureGateTests.swift"]
    ),
    command(
        "validate-native-app-shell-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/NativeAppShellTests.swift"]
    ),
    command(
        "validate-native-app-shell-surface-probe-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/NativeAppShellTests.swift"]
    ),
    command(
        "validate-recording-session-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/RecordingSessionArtifactTests.swift"]
    ),
    command(
        "validate-packaging-field-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/PackagingFieldTestTests.swift"]
    ),
    command(
        "validate-field-runtime-proof",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/FieldReadyRuntimeProofTests.swift"]
    ),
    command(
        "validate-lola-parity-deferred-ledger",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/LoLaParityDeferredFeaturesTests.swift"]
    ),
    command(
        "validate-faster-than-lola-closure",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/FasterThanLoLaClosureTests.swift"]
    ),
    command(
        "validate-goal-codewise-closure-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/GoalCodewiseClosureTests.swift"]
    ),
    command(
        "validate-goal-runtime-evidence-template-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/GoalRuntimeEvidenceTemplateTests.swift"]
    ),
    command(
        "validate-goal-runtime-preflight-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/GoalRuntimePreflightTests.swift"]
    ),
    command(
        "validate-goal-completion-audit-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/GoalCompletionAuditTests.swift"]
    ),
    command(
        "validate-current-evidence-status-matrix-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/CurrentEvidenceStatusMatrixTests.swift"]
    ),
    command(
        "validate-release-hardening-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/ReleaseHardeningTests.swift"]
    ),
    command(
        "validate-open-source-release-readiness-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        ["Tests/OpenLolaCoreTests/OpenSourceReleaseReadinessTests.swift"]
    )
]
