// Declares external-connector command rows separately so connector CLI coverage can be audited without expanding the core runtime table.
import Foundation

let milestoneRuntimeExternalCommands: [CLICommandInventoryEntry] = [
    command(
        "external-connector-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "external-connector-report-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "external-connector-session-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "external-connector-connection-plan-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "external-connector-nmp-plan-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "external-connector-nmp-preflight-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "external-connector-nmp-endpoint-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "external-connector-nmp-workflow-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "external-connector-executable-preflight-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "lola-capture-decode",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "lola-packet-fixture-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "lola-media-report-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "lola-raw-link-tx-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "lola-raw-link-rx-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "lola-udp-media-tx-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "lola-udp-media-rx-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "validate-external-connector-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-external-connector-session-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-external-connector-connection-plan",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-external-connector-nmp-plan",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-external-connector-nmp-preflight",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-external-connector-nmp-endpoint-run",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-external-connector-nmp-workflow",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-external-connector-executable-preflight-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-lola-capture-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-lola-packet-fixture-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "validate-lola-media-session-report",
        .validator,
        "Sources/open-lola/Commands/Validation/MilestoneValidationCommands.swift",
        []
    ),
    command(
        "release-hardening-synthetic-smoke",
        .syntheticSmoke,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "release-hardening-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "open-source-release-readiness-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    ),
    command(
        "drift-plc-run",
        .run,
        "Sources/open-lola/Commands/MilestoneCommands.swift",
        []
    )
]
