// Centralizes application storage keys, preventing persistence identifiers from being duplicated across views.
import OpenLolaCore

enum AppStorageKeys {
    // Usage map:
    // - Execution keys are read/written by AppShellSettingsView and hydrated through AppShellStoredDefaults.
    // - Peer, audio, video, and AV profile keys hydrate NativeAppShellDirectPeerCommandFields.
    // - Preview keys hydrate AppPreviewReceiverState.
    static let selectedSection = "selectedAppShellSection"
    static let selectedSettingsTab = "openLola.selectedSettingsTab"
    static let sessionMode = "openLola.sessionMode"
    static let controlMode = "openLola.controlMode"
    static let executablePath = "openLola.executablePath"
    static let planPath = "openLola.planPath"
    static let supervisorReportPath = "openLola.supervisorReportPath"
    static let executionMode = "openLola.executionMode"
    static let requirePreflight = "openLola.requirePreflight"
    static let executionMacASSH = "openLola.execution.macASSH"
    static let executionMacBSSH = "openLola.execution.macBSSH"
    static let executionMacAWorkingDirectory = "openLola.execution.macAWorkingDirectory"
    static let executionMacBWorkingDirectory = "openLola.execution.macBWorkingDirectory"
    static let executionSSHExecutable = "openLola.execution.sshExecutable"
    static let executionSCPExecutable = "openLola.execution.scpExecutable"
    static let role = "openLola.role"
    static let localPeer = "openLola.localPeer"
    static let remotePeer = "openLola.remotePeer"
    static let localHost = "openLola.localHost"
    static let remoteHost = "openLola.remoteHost"
    static let controlPort = "openLola.controlPort"
    static let remoteControlPort = "openLola.remoteControlPort"
    static let audioPort = "openLola.audioPort"
    static let videoPort = "openLola.videoPort"
    static let metricsPort = "openLola.metricsPort"
    static let outputPath = "openLola.outputPath"
    static let channelCount = "openLola.channelCount"
    static let sampleRate = "openLola.sampleRate"
    static let frames = "openLola.frames"
    static let duration = "openLola.duration"
    static let sampleFormat = "openLola.sampleFormat"
    static let audioTransport = "openLola.audioTransport"
    static let audioCompression = "openLola.audioCompression"
    static let videoWidth = "openLola.videoWidth"
    static let videoHeight = "openLola.videoHeight"
    static let videoPixelFormat = "openLola.videoPixelFormat"
    static let videoCompression = "openLola.videoCompression"
    static let videoFrameRate = "openLola.videoFrameRate"
    static let videoStreamID = "openLola.videoStreamID"
    static let timeoutSeconds = "openLola.timeoutSeconds"
    static let avProfile = "openLola.avProfile"
    static let rxBufferProfile = "openLola.rxBufferProfile"
    static let preview = "openLola.preview"
    static let audioPreviewEnabled = "openLola.audioPreviewEnabled"
    static let videoPreviewEnabled = "openLola.videoPreviewEnabled"
    static let showSafeFrame = "openLola.showSafeFrame"
    static let monitorGain = "openLola.monitorGain"
    static let remoteReturnBlend = "openLola.remoteReturnBlend"
    static let videoScale = "openLola.videoScale"
    static let visibleStreams = "openLola.visibleStreams"
    static let selectedVideoStream = "openLola.selectedVideoStream"
    static let operatorPlanArtifactPath = "openLola.operatorPlanArtifactPath"
    static let operatorSupervisorReportPath = "openLola.operatorSupervisorReportPath"
    static let operatorMacASSH = "openLola.operatorMacASSH"
    static let operatorMacBSSH = "openLola.operatorMacBSSH"
    static let windowsLoLaLocalHost = "openLola.windowsLoLa.localHost"
    static let windowsLoLaWindowsHost = "openLola.windowsLoLa.windowsHost"
    static let windowsLoLaRole = "openLola.windowsLoLa.role"
    static let windowsLoLaControlPort = "openLola.windowsLoLa.controlPort"
    static let windowsLoLaAudioPort = "openLola.windowsLoLa.audioPort"
    static let windowsLoLaVideoPort = "openLola.windowsLoLa.videoPort"
    static let windowsLoLaMediaMode = "openLola.windowsLoLa.mediaMode"
    static let windowsLoLaPayloadMode = "openLola.windowsLoLa.payloadMode"
    static let windowsLoLaVideoWidth = "openLola.windowsLoLa.videoWidth"
    static let windowsLoLaVideoHeight = "openLola.windowsLoLa.videoHeight"
    static let windowsLoLaVideoFrameRate = "openLola.windowsLoLa.videoFrameRate"
    static let windowsLoLaVideoBitsPerPixel = "openLola.windowsLoLa.videoBitsPerPixel"
    static let windowsLoLaDuration = "openLola.windowsLoLa.duration"
    static let windowsLoLaOutputPath = "openLola.windowsLoLa.outputPath"
    static let windowsLoLaSampleRate = "openLola.windowsLoLa.sampleRate"
    static let windowsLoLaFrames = "openLola.windowsLoLa.frames"
    static let windowsLoLaChannelCount = "openLola.windowsLoLa.channelCount"
    static let windowsLoLaCompression = "openLola.windowsLoLa.compression"
    static let windowsLoLaBayer = "openLola.windowsLoLa.bayer"
    static let jackTripLocalHost = "openLola.jackTrip.localHost"
    static let jackTripPeerHost = "openLola.jackTrip.peerHost"
    static let jackTripRole = "openLola.jackTrip.role"
    static let jackTripAudioPort = "openLola.jackTrip.audioPort"
    static let jackTripPeerAudioPort = "openLola.jackTrip.peerAudioPort"
    static let jackTripVideoPort = "openLola.jackTrip.videoPort"
    static let jackTripMediaMode = "openLola.jackTrip.mediaMode"
    static let jackTripDuration = "openLola.jackTrip.duration"
    static let jackTripOutputPath = "openLola.jackTrip.outputPath"
    static let ultraGridLocalHost = "openLola.ultraGrid.localHost"
    static let ultraGridPeerHost = "openLola.ultraGrid.peerHost"
    static let ultraGridRole = "openLola.ultraGrid.role"
    static let ultraGridAudioPort = "openLola.ultraGrid.audioPort"
    static let ultraGridPeerAudioPort = "openLola.ultraGrid.peerAudioPort"
    static let ultraGridVideoPort = "openLola.ultraGrid.videoPort"
    static let ultraGridMediaMode = "openLola.ultraGrid.mediaMode"
    static let ultraGridDuration = "openLola.ultraGrid.duration"
    static let ultraGridOutputPath = "openLola.ultraGrid.outputPath"
}

enum AppOperatorArtifactDefaults {
    static let planArtifactPath = NativeAppShellExecutionPaths.defaultPlanPath()
    static let supervisorReportPath = NativeAppShellExecutionPaths.defaultSupervisorReportPath()
    static let macASSH = "mac-a.local"
    static let macBSSH = "mac-b.local"
}
